spring.application.name=task-manager
spring.datasource.url=jdbc:postgresql://localhost:5432/task_management_db
spring.datasource.username=task_user_admin
spring.datasource.password=Admin_task
spring.datasource.driver-class-name=org.postgresql.Driver

# Validate existing tables only (no schema generation or migration scripts)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT settings
app.jwt.secret=Rk9SX0RFVkVMT1BNRU5UX09OTFlfQ0hBTkdFX1RISVNfU0VDUkVUX0tFWV8xMjM0NTY3ODkw
app.jwt.expiration-ms=86400000